# Generated by Django 5.1.4 on 2025-06-17 16:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('AppMembre', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleBlog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=100)),
                ('contenue', models.TextField()),
                ('image', models.ImageField(upload_to='static/images/blog/')),
                ('date_publication', models.DateTimeField(auto_now_add=True)),
                ('publie', models.BooleanField(default=False, verbose_name='publié')),
                ('auteur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AppMembre.utilisateur')),
            ],
            options={
                'verbose_name': 'Article de blog',
                'verbose_name_plural': 'Articles de blog',
                'ordering': ['-date_publication'],
            },
        ),
        migrations.CreateModel(
            name='CommentaireBlog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('date_commentaire', models.DateTimeField(auto_now_add=True)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AppBlog.articleblog')),
                ('auteur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AppMembre.utilisateur')),
            ],
            options={
                'verbose_name': 'Commentaire sur article',
                'verbose_name_plural': 'Commentaires sur articles',
                'ordering': ['date_commentaire'],
            },
        ),
    ]
