# Generated by Django 5.1.4 on 2025-06-19 07:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppEvenements', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='evenement',
            old_name='nombre_participants',
            new_name='participants',
        ),
    ]
