# Generated by Django 5.1.4 on 2025-06-19 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppEvenements', '0002_rename_nombre_participants_evenement_participants'),
        ('AppMembre', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='evenement',
            name='participants',
        ),
        migrations.AddField(
            model_name='evenement',
            name='nombre_participants',
            field=models.ManyToManyField(blank=True, related_name='evenement_participes', through='AppEvenements.ParticipationEvenement', to='AppMembre.utilisateur'),
        ),
    ]
