# Generated by Django 5.1.4 on 2025-06-19 14:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppEvenements', '0003_remove_evenement_participants_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='activite',
            options={'ordering': ['-date_activites'], 'verbose_name': 'Activité', 'verbose_name_plural': 'Activités'},
        ),
        migrations.RenameField(
            model_name='activite',
            old_name='date_organisation',
            new_name='date_activites',
        ),
    ]
