# Generated by Django 5.1.4 on 2025-06-17 16:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('AppMembre', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Activite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('date_organisation', models.DateField()),
                ('horaire_debut', models.TimeField()),
                ('horaire_fin', models.TimeField(blank=True, null=True)),
                ('lieu', models.CharField(max_length=200)),
                ('image', models.ImageField(blank=True, null=True, upload_to='static/images/activites/', verbose_name='Image')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('createur', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='AppMembre.utilisateur', verbose_name='Créateur')),
                ('participants', models.ManyToManyField(blank=True, related_name='activites_participes', to='AppMembre.utilisateur')),
            ],
            options={
                'verbose_name': 'Activité',
                'verbose_name_plural': 'Activités',
                'ordering': ['-date_organisation'],
            },
        ),
        migrations.CreateModel(
            name='Evenement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('date_debut', models.DateTimeField()),
                ('date_fin', models.DateTimeField()),
                ('lieu', models.CharField(max_length=200)),
                ('nombre_participant_max', models.PositiveIntegerField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='static/images/evenements')),
                ('statut', models.CharField(choices=[('en_attent', 'En attente'), ('en_cours', 'En cours'), ('termine', 'Terminé'), ('annule', 'Annulé')], default='en_attent', max_length=10)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('createur', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='AppMembre.utilisateur')),
                ('participants', models.ManyToManyField(blank=True, related_name='evenement_participes', to='AppMembre.utilisateur')),
            ],
            options={
                'verbose_name': 'Événement',
                'verbose_name_plural': 'Événements',
                'ordering': ['-date_debut'],
            },
        ),
        migrations.CreateModel(
            name='ParticipationActivite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_inscription', models.DateTimeField(auto_now_add=True)),
                ('present', models.BooleanField(default=False)),
                ('activite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AppEvenement.activite')),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AppMembre.utilisateur')),
            ],
            options={
                'verbose_name': 'Participation à une activité',
                'verbose_name_plural': 'Participations aux activités',
                'unique_together': {('activite', 'participant')},
            },
        ),
        migrations.CreateModel(
            name='ParticipationEvenement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_inscription', models.DateTimeField(auto_now_add=True)),
                ('present', models.BooleanField(default=False)),
                ('evenement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AppEvenement.evenement')),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AppMembre.utilisateur')),
            ],
            options={
                'verbose_name': 'Participation à un événement',
                'verbose_name_plural': 'Participations aux événements',
                'unique_together': {('evenement', 'participant')},
            },
        ),
    ]
