# Generated by Django 5.1.4 on 2025-06-18 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppEvenement', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evenement',
            name='statut',
            field=models.CharField(choices=[('prochainement', 'Prochainement'), ('en_cours', 'En cours'), ('termine', 'Terminé'), ('annule', 'Annulé')], default='en_attent', max_length=15),
        ),
    ]
