# Generated by Django 5.1.4 on 2025-06-18 18:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppEvenement', '0002_alter_evenement_statut'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='evenement',
            name='statut',
        ),
    ]
