# Generated by Django 5.1.4 on 2025-06-27 16:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('AppEvenements', '0004_alter_activite_options_and_more'),
        ('AppMembre', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Actualite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=50)),
                ('contenue', models.TextField()),
                ('date_publication', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('etat', models.CharField(choices=[('brouillon', 'Brouillon'), ('en_attente', 'En attente de validation'), ('publie', 'Publié'), ('rejete', 'Rejeté')], default='brouillon', max_length=20)),
                ('activite', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='AppEvenements.activite')),
                ('auteur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AppMembre.utilisateur')),
                ('evenement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='AppEvenements.evenement')),
            ],
            options={
                'verbose_name': 'Actualité',
                'verbose_name_plural': 'Actualités',
                'ordering': ['-date_publication'],
            },
        ),
        migrations.CreateModel(
            name='Commentaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('date_commentaire', models.DateTimeField(auto_now_add=True)),
                ('actualite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AppActualite.actualite')),
                ('auteur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AppMembre.utilisateur')),
            ],
            options={
                'verbose_name': 'Commentaire',
                'verbose_name_plural': 'Commentaires',
                'ordering': ['date_commentaire'],
            },
        ),
        migrations.CreateModel(
            name='ImageActualite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='static/images/actualites/')),
                ('ordre', models.PositiveIntegerField(default=0)),
                ('actualite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='AppActualite.actualite')),
            ],
            options={
                'ordering': ['ordre'],
            },
        ),
    ]
