# Generated by Django 5.1.4 on 2025-06-27 16:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppActualite', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='imageactualite',
            options={'ordering': ['ordre'], 'verbose_name': 'imageActualite', 'verbose_name_plural': 'imageActualite'},
        ),
    ]
