# Generated by Django 5.1.4 on 2025-06-13 18:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=255)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Utilisateur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=20)),
                ('prenom', models.CharField(max_length=50)),
                ('date_naissance', models.DateField()),
                ('telephone', models.CharField(max_length=20)),
                ('photo', models.ImageField(upload_to='static/images/membres/')),
                ('email', models.EmailField(max_length=254)),
                ('mot_de_passe', models.TextField()),
                ('date_inscription', models.DateField(auto_now_add=True)),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AppMembre.role')),
            ],
            options={
                'verbose_name': 'Utilisateur',
                'verbose_name_plural': 'Utilisateurs',
            },
        ),
        migrations.CreateModel(
            name='Cotisation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant', models.DecimalField(decimal_places=2, max_digits=10)),
                ('periode', models.CharField(max_length=50)),
                ('date_limite_paiement', models.DateField()),
                ('date_paiement', models.DateField(auto_now_add=True)),
                ('reference_paiement', models.CharField(blank=True, max_length=100, null=True)),
                ('statut', models.CharField(choices=[('paye', 'Payé'), ('non_paye', 'Non payé')], default='non_paye', max_length=20)),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AppMembre.utilisateur')),
            ],
            options={
                'verbose_name': 'Cotisation',
                'verbose_name_plural': 'Cotisations',
                'ordering': ['-periode', 'utilisateur'],
            },
        ),
    ]
