# Generated by Django 5.1.4 on 2025-07-03 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppMembre', '0002_cotisation_paiement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cotisation',
            name='montant',
            field=models.IntegerField(),
        ),
    ]
