# Generated by Django 5.1.4 on 2025-07-03 19:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppMembre', '0003_alter_cotisation_montant'),
    ]

    operations = [
        migrations.CreateModel(
            name='Paiement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_paiement', models.DateField(auto_now_add=True)),
                ('montant', models.DecimalField(decimal_places=2, max_digits=10)),
                ('methode_paiement', models.CharField(choices=[('espece', 'Espèces'), ('cheque', 'Chèque'), ('mobile', 'Mobile Money'), ('carte', 'Carte bancaire')], max_length=50)),
                ('numero_compte', models.CharField(max_length=15)),
                ('preuve_paiement', models.FileField(blank=True, null=True, upload_to='static/paiements/preuves/')),
                ('statut', models.CharField(choices=[('en_attente', 'En attente'), ('valide', 'Validé'), ('refuse', 'Refusé')], default='en_attente', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('cotisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AppMembre.cotisation')),
                ('membre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AppMembre.utilisateur')),
            ],
            options={
                'ordering': ['-date_paiement'],
            },
        ),
    ]
