# Generated by Django 5.1.4 on 2025-07-03 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppMembre', '0004_paiement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paiement',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
